### ISSUE TITLE
Replit version not supported yet, sir?

### ISSUE THREAD

**Issue by 0zunu** [MhankBarBar/hitori-bot#9]

**Comment by MhankBarBar** [comment]
i think replit cannot run nodejs and python at the same time

**Comment by MhankBarBar** [comment]
![image](https://github.com/MhankBarBar/hitori-bot/assets/55822959/74ebdcaa-88b6-4a75-8c22-60f9aee55d1e)
ahh its can, but not recommended because ram on replit is only 512, the response time while executing commands take >1 minute.

if you want to try just go to [*my replit*](https://replit.com/@MhankBarBar/hitori-bot) then fork and run
